export const documents = [
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "Name of document",
		type: "Newsletter",
		subtype: "Blue Nile",
		month: "June",
		year: 2021,
		img: "/images/documentImage.png",
	},
];
