export const documents = [
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "تقرير نصف شهري",
		subtype: "Blue Nile",
		month: "يونيو",
		year: 2021,
		img: "/images/documentImage.png",
	},
];
