export const hero_info = {
	bimonthly: "معلومات عن التقارير نصف الشهرية",
	advocacy: "معلومات عن تقارير المناصرة",
	meetings: "معلومات عن تقارير الإجتماعات",
	monthly: "معلومات عن التقارير الشهرية",
};
export const types = [
	"شهري",
	"نصف شهري",
	"مناصرة",
	"إجتماعات",
	"الإنتقالية",
];
export const locations = ["النيل الأزرق", "دارفور", "قومية"];
export const years = [2021, 2020];
export const months = [
	"يناير",
	"فبراير",
	"مارس",
	"ابريل",
	"مايو",
	"يونيو",
	"يوليو",
	"أغسطس",
	"سبتمبر",
	"اكتوبر",
	"نوفمبر",
	"ديسمبر",
];
export const documents = [
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "النيل الأزرق",
		month: "يونيو",
		year: 2021,
		filter: ['bimonthly', 'jun', 'BN', 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "النيل الأزرق",
		month: "يونيو",
		year: 2020,
		filter: ['bimonthly', 'june', 'BN', 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "النيل الأزرق",
		month: "يوليو",
		year: 2020,
		filter: ['bimonthly', 'june', 'BN', 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "النيل الأزرق",
		month: "يوليو",
		year: 2020,
		filter: ['bimonthly', 'june', 'BN', 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "يناير",
		year: 2020,
		filter: ['bimonthly', 'june', 'BN', 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "يناير",
		year: 2021,
		filter: ['bimonthly', 'june', 'BN', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "فبراير",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "فبراير",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "مناصرة",
		subtype: "دارفور",
		month: "مارس",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "دارفور",
		month: "مارس",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "إجتماعات",
		subtype: "قومية",
		month: "أغسطس",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "الإنتقالية",
		subtype: "قومية",
		month: "أغسطس",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "الإنتقالية",
		subtype: "قومية",
		month: "ديسمبر",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "قومية",
		month: "ديسمبر",
		year: 2021,
		filter: ['monthly', 'national', 'aug', 2021],
		img: "/images/documentImage.png",
	},
];
