import { ar } from "../locales/ar";
import { en } from "../locales/en";
import { useRouter } from "next/router";

export const hero_info = {
	bimonthly: `يعمل فريق التنسيق على مشاركة المساهمين/ات بالمنتدي و الفاعلين/ات بالمجتمع المدني على تقارير نصف شهري ( كل 14 يوما ) ، تتناول أهم التحديثات المتصلة بـــــــ : السياق السياسي - الأوضاع الاقتصادية - الأوضاع الأمنية - تحديثات المتصلة بالمجتمع المدني و المجموعات القاعدية - القضايا الطارئة. وذلك بمناطق عمل المنتدى التفاكري المختلفة (ولايات إقليم دارفور - ولايات إقليم شرق السودان - ولاية جنوب كردفان " مناطق سيطرة الحكومة السودانية " - ولاية النيل الأزرق " مناطق سيطرة الحكومة السودانية " - مناطق سيطرة الحركة الشعبية لتحرير السودان - شمال، في ولايتي " النيل الأزرق وجنوب كردفان ").`,
	advocacy: `تستعرض هذه النشرة التي يتم اصدارها كل شهرين بواسطة فريق التنسيق للمنتدى، أهم القضايا التي تتطلب تدخلات عاجلة ومناصرة بواسطة المجتمع المدني على المستوى الوطني او الاقليمي، أو ذوي الصلة من المنظمات الدولية، والتي يتم التوصل إليها من خلال تحليل نتائج توصيات الاجتماعات والأنشطة الإقليمية والولائية التي يتم تنفيذها بواسطة فريق التنسيق بمناطق عمله، أيضا من خلال المقابلات و الجلسات التشاورية مع مساهمي المنتدي و الفاعلين/ات بالمجتمع المدني `,
	meetings: `يقوم المنتدى التفاكري بإصدار نشرة ربع سنوية تتناول إحدى القضايا الفاعلة و المؤثرة على المستوى الوطني من خلال إجراء مقابلات و جلسات تشاورية لاستطلاع آراء مساهمين/ات المنتدى او الفاعلين/ات بهذه القضايا. `,
	monthly: `من خلال هذه النشرة يقوم فريق التنسيق للمنتدى التفاكري، باستعراض أهم القضايا الطارئة والمستجدات المتصلة بالأوضاع في مناطق سيطرة الحكومة السودانية ومناطق سيطرة حركات الكفاح المسلح، حيث تحوي هذه النشرات اهم التحليلات المتصلة بالأوضاع السياسية والاقتصادية والأمنية والقضايا الطارئة من وجهة نظر مساهمي /ات المنتدى و الفاعلين/ات بالمجتمع المدني بهذه المناطق. `,
};
export const ar_types = [
	"شهرية",
	"نصف شهرية",
	"مناصرة",
	"إجتماعات",
	"إنتقال",
];
export const en_types = [
	"monthly",
	"bi-monthly",
	"advocacy",
	"meetings",
	"transitional",
];
export const locations = [
	"النيل الأزرق",
	"دارفور",
	"قومية",
	"جنوب كردفان",
	"الشرق",
];
export const years = [2021, 2020];
export const months = [
	"يناير",
	"فبراير",
	"مارس",
	"ابريل",
	"مايو",
	"يونيو",
	"يوليو",
	"أغسطس",
	"سبتمبر",
	"اكتوبر",
	"نوفمبر",
	"ديسمبر",
];
export const documents = [
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "النيل الأزرق",
		month: "يونيو",
		year: 2021,
		filter: ["bimonthly", "jun", "BN", 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "النيل الأزرق",
		month: "يونيو",
		year: 2020,
		filter: ["bimonthly", "june", "BN", 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "النيل الأزرق",
		month: "يوليو",
		year: 2020,
		filter: ["bimonthly", "june", "BN", 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "النيل الأزرق",
		month: "يوليو",
		year: 2020,
		filter: ["bimonthly", "june", "BN", 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "يناير",
		year: 2020,
		filter: ["bimonthly", "june", "BN", 2020],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "يناير",
		year: 2021,
		filter: ["bimonthly", "june", "BN", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "فبراير",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "شهري",
		subtype: "دارفور",
		month: "فبراير",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "مناصرة",
		subtype: "دارفور",
		month: "مارس",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "دارفور",
		month: "مارس",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "إجتماعات",
		subtype: "قومية",
		month: "أغسطس",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "الإنتقالية",
		subtype: "قومية",
		month: "أغسطس",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "الإنتقالية",
		subtype: "قومية",
		month: "ديسمبر",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
	{
		title: "إسم المستند",
		type: "نصف شهري",
		subtype: "قومية",
		month: "ديسمبر",
		year: 2021,
		filter: ["monthly", "national", "aug", 2021],
		img: "/images/documentImage.png",
	},
];
